# Generated by Django 4.2.7 on 2024-01-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_details/media/uploads/')),
                ('book_name', models.CharField(max_length=30)),
                ('book_descriptions', models.TextField()),
                ('book_price', models.CharField(max_length=40)),
                ('borrow_status', models.BinaryField(default=False)),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_category.book_category')),
            ],
        ),
    ]
