# Generated by Django 4.2.7 on 2024-01-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_details', '0002_alter_book_details_borrow_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_details',
            name='borrow_status',
        ),
    ]
