# Generated by Django 4.2.7 on 2024-01-06 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
        ('book_details', '0005_borrowmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitormodel'),
        ),
    ]
