# Generated by Django 4.2.7 on 2024-01-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Borrow'), (3, 'Return')], null=True),
        ),
    ]
