# Generated by Django 4.2.7 on 2024-01-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transactionmodel_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='transaction_type',
        ),
    ]
